
package py.com.personal.vas;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfstring;
import org.datacontract.schemas._2004._07.mimundoussd.ArrayOfPlanes;
import org.datacontract.schemas._2004._07.mimundoussd.Facturas;
import org.datacontract.schemas._2004._07.mimundoussd.Personas;
import org.datacontract.schemas._2004._07.mimundoussd.Saldos;
import org.datacontract.schemas._2004._07.mimundoussd.ServicioAdicional;
import org.datacontract.schemas._2004._07.mimundoussd.Usuarios;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IService1", targetNamespace = "http://vas.personal.com.py")
@XmlSeeAlso({
    com.microsoft.schemas._2003._10.serialization.ObjectFactory.class,
    com.microsoft.schemas._2003._10.serialization.arrays.ObjectFactory.class,
    org.datacontract.schemas._2004._07.mimundoussd.ObjectFactory.class,
    py.com.personal.vas.ObjectFactory.class
})
public interface IService1 {


    /**
     * 
     * @param aplicacion
     * @param servicio
     * @param usuario
     * @param lineaOrigen
     * @param pass
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "VerificarServicio", action = "http://vas.personal.com.py/IService1/VerificarServicio")
    @WebResult(name = "VerificarServicioResult", targetNamespace = "http://vas.personal.com.py")
    @RequestWrapper(localName = "VerificarServicio", targetNamespace = "http://vas.personal.com.py", className = "py.com.personal.vas.VerificarServicio")
    @ResponseWrapper(localName = "VerificarServicioResponse", targetNamespace = "http://vas.personal.com.py", className = "py.com.personal.vas.VerificarServicioResponse")
    public Boolean verificarServicio(
        @WebParam(name = "Usuario", targetNamespace = "http://vas.personal.com.py")
        String usuario,
        @WebParam(name = "Pass", targetNamespace = "http://vas.personal.com.py")
        String pass,
        @WebParam(name = "Aplicacion", targetNamespace = "http://vas.personal.com.py")
        String aplicacion,
        @WebParam(name = "LineaOrigen", targetNamespace = "http://vas.personal.com.py")
        String lineaOrigen,
        @WebParam(name = "Servicio", targetNamespace = "http://vas.personal.com.py")
        String servicio);

    /**
     * 
     * @param aplicacion
     * @param usuario
     * @param lineaOrigen
     * @param pass
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ConsultaSaldoKml", action = "http://vas.personal.com.py/IService1/ConsultaSaldoKml")
    @WebResult(name = "ConsultaSaldoKmlResult", targetNamespace = "http://vas.personal.com.py")
    @RequestWrapper(localName = "ConsultaSaldoKml", targetNamespace = "http://vas.personal.com.py", className = "py.com.personal.vas.ConsultaSaldoKml")
    @ResponseWrapper(localName = "ConsultaSaldoKmlResponse", targetNamespace = "http://vas.personal.com.py", className = "py.com.personal.vas.ConsultaSaldoKmlResponse")
    public String consultaSaldoKml(
        @WebParam(name = "Usuario", targetNamespace = "http://vas.personal.com.py")
        String usuario,
        @WebParam(name = "Pass", targetNamespace = "http://vas.personal.com.py")
        String pass,
        @WebParam(name = "Aplicacion", targetNamespace = "http://vas.personal.com.py")
        String aplicacion,
        @WebParam(name = "LineaOrigen", targetNamespace = "http://vas.personal.com.py")
        String lineaOrigen);

    /**
     * 
     * @param aplicacion
     * @param usuario
     * @param lineaOrigen
     * @param pass
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ClubPuntoPorVender", action = "http://vas.personal.com.py/IService1/ClubPuntoPorVender")
    @WebResult(name = "ClubPuntoPorVenderResult", targetNamespace = "http://vas.personal.com.py")
    @RequestWrapper(localName = "ClubPuntoPorVender", targetNamespace = "http://vas.personal.com.py", className = "py.com.personal.vas.ClubPuntoPorVender")
    @ResponseWrapper(localName = "ClubPuntoPorVenderResponse", targetNamespace = "http://vas.personal.com.py", className = "py.com.personal.vas.ClubPuntoPorVenderResponse")
    public String clubPuntoPorVender(
        @WebParam(name = "Usuario", targetNamespace = "http://vas.personal.com.py")
        String usuario,
        @WebParam(name = "Pass", targetNamespace = "http://vas.personal.com.py")
        String pass,
        @WebParam(name = "Aplicacion", targetNamespace = "http://vas.personal.com.py")
        String aplicacion,
        @WebParam(name = "LineaOrigen", targetNamespace = "http://vas.personal.com.py")
        String lineaOrigen);

    /**
     * 
     * @param aplicacion
     * @param usuario
     * @param lineaOrigen
     * @param pass
     * @return
     *     returns com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfstring
     */
    @WebMethod(operationName = "ObtenerUltimas3Facturas", action = "http://vas.personal.com.py/IService1/ObtenerUltimas3Facturas")
    @WebResult(name = "ObtenerUltimas3FacturasResult", targetNamespace = "http://vas.personal.com.py")
    @RequestWrapper(localName = "ObtenerUltimas3Facturas", targetNamespace = "http://vas.personal.com.py", className = "py.com.personal.vas.ObtenerUltimas3Facturas")
    @ResponseWrapper(localName = "ObtenerUltimas3FacturasResponse", targetNamespace = "http://vas.personal.com.py", className = "py.com.personal.vas.ObtenerUltimas3FacturasResponse")
    public ArrayOfstring obtenerUltimas3Facturas(
        @WebParam(name = "Usuario", targetNamespace = "http://vas.personal.com.py")
        String usuario,
        @WebParam(name = "Pass", targetNamespace = "http://vas.personal.com.py")
        String pass,
        @WebParam(name = "Aplicacion", targetNamespace = "http://vas.personal.com.py")
        String aplicacion,
        @WebParam(name = "LineaOrigen", targetNamespace = "http://vas.personal.com.py")
        String lineaOrigen);

    /**
     * 
     * @param aplicacion
     * @param usuario
     * @param lineaOrigen
     * @param pass
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "VerificaPin", action = "http://vas.personal.com.py/IService1/VerificaPin")
    @WebResult(name = "VerificaPinResult", targetNamespace = "http://vas.personal.com.py")
    @RequestWrapper(localName = "VerificaPin", targetNamespace = "http://vas.personal.com.py", className = "py.com.personal.vas.VerificaPin")
    @ResponseWrapper(localName = "VerificaPinResponse", targetNamespace = "http://vas.personal.com.py", className = "py.com.personal.vas.VerificaPinResponse")
    public Boolean verificaPin(
        @WebParam(name = "Usuario", targetNamespace = "http://vas.personal.com.py")
        String usuario,
        @WebParam(name = "Pass", targetNamespace = "http://vas.personal.com.py")
        String pass,
        @WebParam(name = "Aplicacion", targetNamespace = "http://vas.personal.com.py")
        String aplicacion,
        @WebParam(name = "LineaOrigen", targetNamespace = "http://vas.personal.com.py")
        String lineaOrigen);

    /**
     * 
     * @param aplicacion
     * @param pin
     * @param usuario
     * @param lineaDestino
     * @param lineaOrigen
     * @param monto
     * @param pass
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "TransferenciaP2P", action = "http://vas.personal.com.py/IService1/TransferenciaP2P")
    @WebResult(name = "TransferenciaP2PResult", targetNamespace = "http://vas.personal.com.py")
    @RequestWrapper(localName = "TransferenciaP2P", targetNamespace = "http://vas.personal.com.py", className = "py.com.personal.vas.TransferenciaP2P")
    @ResponseWrapper(localName = "TransferenciaP2PResponse", targetNamespace = "http://vas.personal.com.py", className = "py.com.personal.vas.TransferenciaP2PResponse")
    public String transferenciaP2P(
        @WebParam(name = "Usuario", targetNamespace = "http://vas.personal.com.py")
        String usuario,
        @WebParam(name = "Pass", targetNamespace = "http://vas.personal.com.py")
        String pass,
        @WebParam(name = "Aplicacion", targetNamespace = "http://vas.personal.com.py")
        String aplicacion,
        @WebParam(name = "LineaOrigen", targetNamespace = "http://vas.personal.com.py")
        String lineaOrigen,
        @WebParam(name = "LineaDestino", targetNamespace = "http://vas.personal.com.py")
        String lineaDestino,
        @WebParam(name = "Monto", targetNamespace = "http://vas.personal.com.py")
        String monto,
        @WebParam(name = "Pin", targetNamespace = "http://vas.personal.com.py")
        String pin);

    /**
     * 
     * @param aplicacion
     * @param usuario
     * @param lineaOrigen
     * @param pass
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "VerificaLineaIndividual", action = "http://vas.personal.com.py/IService1/VerificaLineaIndividual")
    @WebResult(name = "VerificaLineaIndividualResult", targetNamespace = "http://vas.personal.com.py")
    @RequestWrapper(localName = "VerificaLineaIndividual", targetNamespace = "http://vas.personal.com.py", className = "py.com.personal.vas.VerificaLineaIndividual")
    @ResponseWrapper(localName = "VerificaLineaIndividualResponse", targetNamespace = "http://vas.personal.com.py", className = "py.com.personal.vas.VerificaLineaIndividualResponse")
    public Boolean verificaLineaIndividual(
        @WebParam(name = "Usuario", targetNamespace = "http://vas.personal.com.py")
        String usuario,
        @WebParam(name = "Pass", targetNamespace = "http://vas.personal.com.py")
        String pass,
        @WebParam(name = "Aplicacion", targetNamespace = "http://vas.personal.com.py")
        String aplicacion,
        @WebParam(name = "LineaOrigen", targetNamespace = "http://vas.personal.com.py")
        String lineaOrigen);

    /**
     * 
     * @param aplicacion
     * @param fechaNac
     * @param usuario
     * @param lineaOrigen
     * @param cedula
     * @param pass
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ActivarRecargaContraFactura", action = "http://vas.personal.com.py/IService1/ActivarRecargaContraFactura")
    @WebResult(name = "ActivarRecargaContraFacturaResult", targetNamespace = "http://vas.personal.com.py")
    @RequestWrapper(localName = "ActivarRecargaContraFactura", targetNamespace = "http://vas.personal.com.py", className = "py.com.personal.vas.ActivarRecargaContraFactura")
    @ResponseWrapper(localName = "ActivarRecargaContraFacturaResponse", targetNamespace = "http://vas.personal.com.py", className = "py.com.personal.vas.ActivarRecargaContraFacturaResponse")
    public String activarRecargaContraFactura(
        @WebParam(name = "Usuario", targetNamespace = "http://vas.personal.com.py")
        String usuario,
        @WebParam(name = "Pass", targetNamespace = "http://vas.personal.com.py")
        String pass,
        @WebParam(name = "Aplicacion", targetNamespace = "http://vas.personal.com.py")
        String aplicacion,
        @WebParam(name = "LineaOrigen", targetNamespace = "http://vas.personal.com.py")
        String lineaOrigen,
        @WebParam(name = "Cedula", targetNamespace = "http://vas.personal.com.py")
        String cedula,
        @WebParam(name = "FechaNac", targetNamespace = "http://vas.personal.com.py")
        String fechaNac);

    /**
     * 
     * @param aplicacion
     * @param servicio
     * @param usuario
     * @param lineaOrigen
     * @param pass
     * @return
     *     returns org.datacontract.schemas._2004._07.mimundoussd.ServicioAdicional
     */
    @WebMethod(operationName = "VerificarServicioNombre", action = "http://vas.personal.com.py/IService1/VerificarServicioNombre")
    @WebResult(name = "VerificarServicioNombreResult", targetNamespace = "http://vas.personal.com.py")
    @RequestWrapper(localName = "VerificarServicioNombre", targetNamespace = "http://vas.personal.com.py", className = "py.com.personal.vas.VerificarServicioNombre")
    @ResponseWrapper(localName = "VerificarServicioNombreResponse", targetNamespace = "http://vas.personal.com.py", className = "py.com.personal.vas.VerificarServicioNombreResponse")
    public ServicioAdicional verificarServicioNombre(
        @WebParam(name = "Usuario", targetNamespace = "http://vas.personal.com.py")
        String usuario,
        @WebParam(name = "Pass", targetNamespace = "http://vas.personal.com.py")
        String pass,
        @WebParam(name = "Aplicacion", targetNamespace = "http://vas.personal.com.py")
        String aplicacion,
        @WebParam(name = "LineaOrigen", targetNamespace = "http://vas.personal.com.py")
        String lineaOrigen,
        @WebParam(name = "Servicio", targetNamespace = "http://vas.personal.com.py")
        String servicio);

    /**
     * 
     * @param aplicacion
     * @param p2PActual
     * @param fechaNac
     * @param usuario
     * @param p2PFinal
     * @param lineaOrigen
     * @param cedula
     * @param pass
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ActivarP2P", action = "http://vas.personal.com.py/IService1/ActivarP2P")
    @WebResult(name = "ActivarP2PResult", targetNamespace = "http://vas.personal.com.py")
    @RequestWrapper(localName = "ActivarP2P", targetNamespace = "http://vas.personal.com.py", className = "py.com.personal.vas.ActivarP2P")
    @ResponseWrapper(localName = "ActivarP2PResponse", targetNamespace = "http://vas.personal.com.py", className = "py.com.personal.vas.ActivarP2PResponse")
    public String activarP2P(
        @WebParam(name = "Usuario", targetNamespace = "http://vas.personal.com.py")
        String usuario,
        @WebParam(name = "Pass", targetNamespace = "http://vas.personal.com.py")
        String pass,
        @WebParam(name = "Aplicacion", targetNamespace = "http://vas.personal.com.py")
        String aplicacion,
        @WebParam(name = "LineaOrigen", targetNamespace = "http://vas.personal.com.py")
        String lineaOrigen,
        @WebParam(name = "Cedula", targetNamespace = "http://vas.personal.com.py")
        String cedula,
        @WebParam(name = "FechaNac", targetNamespace = "http://vas.personal.com.py")
        String fechaNac,
        @WebParam(name = "P2PActual", targetNamespace = "http://vas.personal.com.py")
        String p2PActual,
        @WebParam(name = "P2PFinal", targetNamespace = "http://vas.personal.com.py")
        String p2PFinal);

    /**
     * 
     * @param aplicacion
     * @param usuario
     * @param lineaOrigen
     * @param canal
     * @param pass
     * @return
     *     returns com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfstring
     */
    @WebMethod(operationName = "ObtenerMontosPrestame", action = "http://vas.personal.com.py/IService1/ObtenerMontosPrestame")
    @WebResult(name = "ObtenerMontosPrestameResult", targetNamespace = "http://vas.personal.com.py")
    @RequestWrapper(localName = "ObtenerMontosPrestame", targetNamespace = "http://vas.personal.com.py", className = "py.com.personal.vas.ObtenerMontosPrestame")
    @ResponseWrapper(localName = "ObtenerMontosPrestameResponse", targetNamespace = "http://vas.personal.com.py", className = "py.com.personal.vas.ObtenerMontosPrestameResponse")
    public ArrayOfstring obtenerMontosPrestame(
        @WebParam(name = "Usuario", targetNamespace = "http://vas.personal.com.py")
        String usuario,
        @WebParam(name = "Pass", targetNamespace = "http://vas.personal.com.py")
        String pass,
        @WebParam(name = "Aplicacion", targetNamespace = "http://vas.personal.com.py")
        String aplicacion,
        @WebParam(name = "LineaOrigen", targetNamespace = "http://vas.personal.com.py")
        String lineaOrigen,
        @WebParam(name = "Canal", targetNamespace = "http://vas.personal.com.py")
        String canal);

    /**
     * 
     * @param aplicacion
     * @param usuario
     * @param lineaOrigen
     * @param canal
     * @param monto
     * @param pass
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "AcreditarPrestame", action = "http://vas.personal.com.py/IService1/AcreditarPrestame")
    @WebResult(name = "AcreditarPrestameResult", targetNamespace = "http://vas.personal.com.py")
    @RequestWrapper(localName = "AcreditarPrestame", targetNamespace = "http://vas.personal.com.py", className = "py.com.personal.vas.AcreditarPrestame")
    @ResponseWrapper(localName = "AcreditarPrestameResponse", targetNamespace = "http://vas.personal.com.py", className = "py.com.personal.vas.AcreditarPrestameResponse")
    public String acreditarPrestame(
        @WebParam(name = "Usuario", targetNamespace = "http://vas.personal.com.py")
        String usuario,
        @WebParam(name = "Pass", targetNamespace = "http://vas.personal.com.py")
        String pass,
        @WebParam(name = "Aplicacion", targetNamespace = "http://vas.personal.com.py")
        String aplicacion,
        @WebParam(name = "LineaOrigen", targetNamespace = "http://vas.personal.com.py")
        String lineaOrigen,
        @WebParam(name = "Monto", targetNamespace = "http://vas.personal.com.py")
        String monto,
        @WebParam(name = "Canal", targetNamespace = "http://vas.personal.com.py")
        String canal);

    /**
     * 
     * @param aplicacion
     * @param usuario
     * @param lineaOrigen
     * @param canal
     * @param accion
     * @param pass
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ObtenerEstadoCuentaPrestame", action = "http://vas.personal.com.py/IService1/ObtenerEstadoCuentaPrestame")
    @WebResult(name = "ObtenerEstadoCuentaPrestameResult", targetNamespace = "http://vas.personal.com.py")
    @RequestWrapper(localName = "ObtenerEstadoCuentaPrestame", targetNamespace = "http://vas.personal.com.py", className = "py.com.personal.vas.ObtenerEstadoCuentaPrestame")
    @ResponseWrapper(localName = "ObtenerEstadoCuentaPrestameResponse", targetNamespace = "http://vas.personal.com.py", className = "py.com.personal.vas.ObtenerEstadoCuentaPrestameResponse")
    public String obtenerEstadoCuentaPrestame(
        @WebParam(name = "Usuario", targetNamespace = "http://vas.personal.com.py")
        String usuario,
        @WebParam(name = "Pass", targetNamespace = "http://vas.personal.com.py")
        String pass,
        @WebParam(name = "Aplicacion", targetNamespace = "http://vas.personal.com.py")
        String aplicacion,
        @WebParam(name = "LineaOrigen", targetNamespace = "http://vas.personal.com.py")
        String lineaOrigen,
        @WebParam(name = "Accion", targetNamespace = "http://vas.personal.com.py")
        String accion,
        @WebParam(name = "Canal", targetNamespace = "http://vas.personal.com.py")
        String canal);

    /**
     * 
     * @param aplicacion
     * @param usuario
     * @param lineaOrigen
     * @param canal
     * @param pass
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod(operationName = "ObtenerCantidadPrestamos", action = "http://vas.personal.com.py/IService1/ObtenerCantidadPrestamos")
    @WebResult(name = "ObtenerCantidadPrestamosResult", targetNamespace = "http://vas.personal.com.py")
    @RequestWrapper(localName = "ObtenerCantidadPrestamos", targetNamespace = "http://vas.personal.com.py", className = "py.com.personal.vas.ObtenerCantidadPrestamos")
    @ResponseWrapper(localName = "ObtenerCantidadPrestamosResponse", targetNamespace = "http://vas.personal.com.py", className = "py.com.personal.vas.ObtenerCantidadPrestamosResponse")
    public Integer obtenerCantidadPrestamos(
        @WebParam(name = "Usuario", targetNamespace = "http://vas.personal.com.py")
        String usuario,
        @WebParam(name = "Pass", targetNamespace = "http://vas.personal.com.py")
        String pass,
        @WebParam(name = "Aplicacion", targetNamespace = "http://vas.personal.com.py")
        String aplicacion,
        @WebParam(name = "LineaOrigen", targetNamespace = "http://vas.personal.com.py")
        String lineaOrigen,
        @WebParam(name = "Canal", targetNamespace = "http://vas.personal.com.py")
        String canal);

    /**
     * 
     * @param aplicacion
     * @param usuario
     * @param lineaOrigen
     * @param pass
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ConsultarIlimitado", action = "http://vas.personal.com.py/IService1/ConsultarIlimitado")
    @WebResult(name = "ConsultarIlimitadoResult", targetNamespace = "http://vas.personal.com.py")
    @RequestWrapper(localName = "ConsultarIlimitado", targetNamespace = "http://vas.personal.com.py", className = "py.com.personal.vas.ConsultarIlimitado")
    @ResponseWrapper(localName = "ConsultarIlimitadoResponse", targetNamespace = "http://vas.personal.com.py", className = "py.com.personal.vas.ConsultarIlimitadoResponse")
    public String consultarIlimitado(
        @WebParam(name = "Usuario", targetNamespace = "http://vas.personal.com.py")
        String usuario,
        @WebParam(name = "Pass", targetNamespace = "http://vas.personal.com.py")
        String pass,
        @WebParam(name = "Aplicacion", targetNamespace = "http://vas.personal.com.py")
        String aplicacion,
        @WebParam(name = "LineaOrigen", targetNamespace = "http://vas.personal.com.py")
        String lineaOrigen);

    /**
     * 
     * @param aplicacion
     * @param usuario
     * @param lineaOrigen
     * @param pass
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ReacreditarIlimitado", action = "http://vas.personal.com.py/IService1/ReacreditarIlimitado")
    @WebResult(name = "ReacreditarIlimitadoResult", targetNamespace = "http://vas.personal.com.py")
    @RequestWrapper(localName = "ReacreditarIlimitado", targetNamespace = "http://vas.personal.com.py", className = "py.com.personal.vas.ReacreditarIlimitado")
    @ResponseWrapper(localName = "ReacreditarIlimitadoResponse", targetNamespace = "http://vas.personal.com.py", className = "py.com.personal.vas.ReacreditarIlimitadoResponse")
    public String reacreditarIlimitado(
        @WebParam(name = "Usuario", targetNamespace = "http://vas.personal.com.py")
        String usuario,
        @WebParam(name = "Pass", targetNamespace = "http://vas.personal.com.py")
        String pass,
        @WebParam(name = "Aplicacion", targetNamespace = "http://vas.personal.com.py")
        String aplicacion,
        @WebParam(name = "LineaOrigen", targetNamespace = "http://vas.personal.com.py")
        String lineaOrigen);

    /**
     * 
     * @param value
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetData", action = "http://vas.personal.com.py/IService1/GetData")
    @WebResult(name = "GetDataResult", targetNamespace = "http://vas.personal.com.py")
    @RequestWrapper(localName = "GetData", targetNamespace = "http://vas.personal.com.py", className = "py.com.personal.vas.GetData")
    @ResponseWrapper(localName = "GetDataResponse", targetNamespace = "http://vas.personal.com.py", className = "py.com.personal.vas.GetDataResponse")
    public String getData(
        @WebParam(name = "value", targetNamespace = "http://vas.personal.com.py")
        Integer value);

    /**
     * 
     * @param aplicacion
     * @param usuario
     * @param lineaOrigen
     * @param pass
     * @return
     *     returns org.datacontract.schemas._2004._07.mimundoussd.Saldos
     */
    @WebMethod(operationName = "ObtenerSaldo", action = "http://vas.personal.com.py/IService1/ObtenerSaldo")
    @WebResult(name = "ObtenerSaldoResult", targetNamespace = "http://vas.personal.com.py")
    @RequestWrapper(localName = "ObtenerSaldo", targetNamespace = "http://vas.personal.com.py", className = "py.com.personal.vas.ObtenerSaldo")
    @ResponseWrapper(localName = "ObtenerSaldoResponse", targetNamespace = "http://vas.personal.com.py", className = "py.com.personal.vas.ObtenerSaldoResponse")
    public Saldos obtenerSaldo(
        @WebParam(name = "Usuario", targetNamespace = "http://vas.personal.com.py")
        String usuario,
        @WebParam(name = "Pass", targetNamespace = "http://vas.personal.com.py")
        String pass,
        @WebParam(name = "Aplicacion", targetNamespace = "http://vas.personal.com.py")
        String aplicacion,
        @WebParam(name = "LineaOrigen", targetNamespace = "http://vas.personal.com.py")
        String lineaOrigen);

    /**
     * 
     * @param aplicacion
     * @param usuario
     * @param lineaOrigen
     * @param pass
     * @return
     *     returns org.datacontract.schemas._2004._07.mimundoussd.Facturas
     */
    @WebMethod(operationName = "ObtenerUltimaFactura", action = "http://vas.personal.com.py/IService1/ObtenerUltimaFactura")
    @WebResult(name = "ObtenerUltimaFacturaResult", targetNamespace = "http://vas.personal.com.py")
    @RequestWrapper(localName = "ObtenerUltimaFactura", targetNamespace = "http://vas.personal.com.py", className = "py.com.personal.vas.ObtenerUltimaFactura")
    @ResponseWrapper(localName = "ObtenerUltimaFacturaResponse", targetNamespace = "http://vas.personal.com.py", className = "py.com.personal.vas.ObtenerUltimaFacturaResponse")
    public Facturas obtenerUltimaFactura(
        @WebParam(name = "Usuario", targetNamespace = "http://vas.personal.com.py")
        String usuario,
        @WebParam(name = "Pass", targetNamespace = "http://vas.personal.com.py")
        String pass,
        @WebParam(name = "Aplicacion", targetNamespace = "http://vas.personal.com.py")
        String aplicacion,
        @WebParam(name = "LineaOrigen", targetNamespace = "http://vas.personal.com.py")
        String lineaOrigen);

    /**
     * 
     * @param aplicacion
     * @param usuario
     * @param lineaOrigen
     * @param pass
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "AsociarClubPersonal", action = "http://vas.personal.com.py/IService1/AsociarClubPersonal")
    @WebResult(name = "AsociarClubPersonalResult", targetNamespace = "http://vas.personal.com.py")
    @RequestWrapper(localName = "AsociarClubPersonal", targetNamespace = "http://vas.personal.com.py", className = "py.com.personal.vas.AsociarClubPersonal")
    @ResponseWrapper(localName = "AsociarClubPersonalResponse", targetNamespace = "http://vas.personal.com.py", className = "py.com.personal.vas.AsociarClubPersonalResponse")
    public String asociarClubPersonal(
        @WebParam(name = "Usuario", targetNamespace = "http://vas.personal.com.py")
        String usuario,
        @WebParam(name = "Pass", targetNamespace = "http://vas.personal.com.py")
        String pass,
        @WebParam(name = "Aplicacion", targetNamespace = "http://vas.personal.com.py")
        String aplicacion,
        @WebParam(name = "LineaOrigen", targetNamespace = "http://vas.personal.com.py")
        String lineaOrigen);

    /**
     * 
     * @param aplicacion
     * @param usuario
     * @param lineaOrigen
     * @param pass
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ObtenerPuntosClubPersonal", action = "http://vas.personal.com.py/IService1/ObtenerPuntosClubPersonal")
    @WebResult(name = "ObtenerPuntosClubPersonalResult", targetNamespace = "http://vas.personal.com.py")
    @RequestWrapper(localName = "ObtenerPuntosClubPersonal", targetNamespace = "http://vas.personal.com.py", className = "py.com.personal.vas.ObtenerPuntosClubPersonal")
    @ResponseWrapper(localName = "ObtenerPuntosClubPersonalResponse", targetNamespace = "http://vas.personal.com.py", className = "py.com.personal.vas.ObtenerPuntosClubPersonalResponse")
    public String obtenerPuntosClubPersonal(
        @WebParam(name = "Usuario", targetNamespace = "http://vas.personal.com.py")
        String usuario,
        @WebParam(name = "Pass", targetNamespace = "http://vas.personal.com.py")
        String pass,
        @WebParam(name = "Aplicacion", targetNamespace = "http://vas.personal.com.py")
        String aplicacion,
        @WebParam(name = "LineaOrigen", targetNamespace = "http://vas.personal.com.py")
        String lineaOrigen);

    /**
     * 
     * @param aplicacion
     * @param usuario
     * @param lineaOrigen
     * @param pass
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ObtenerPremiosClubPersonal", action = "http://vas.personal.com.py/IService1/ObtenerPremiosClubPersonal")
    @WebResult(name = "ObtenerPremiosClubPersonalResult", targetNamespace = "http://vas.personal.com.py")
    @RequestWrapper(localName = "ObtenerPremiosClubPersonal", targetNamespace = "http://vas.personal.com.py", className = "py.com.personal.vas.ObtenerPremiosClubPersonal")
    @ResponseWrapper(localName = "ObtenerPremiosClubPersonalResponse", targetNamespace = "http://vas.personal.com.py", className = "py.com.personal.vas.ObtenerPremiosClubPersonalResponse")
    public String obtenerPremiosClubPersonal(
        @WebParam(name = "Usuario", targetNamespace = "http://vas.personal.com.py")
        String usuario,
        @WebParam(name = "Pass", targetNamespace = "http://vas.personal.com.py")
        String pass,
        @WebParam(name = "Aplicacion", targetNamespace = "http://vas.personal.com.py")
        String aplicacion,
        @WebParam(name = "LineaOrigen", targetNamespace = "http://vas.personal.com.py")
        String lineaOrigen);

    /**
     * 
     * @param aplicacion
     * @param usuario
     * @param lineaOrigen
     * @param pass
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "PrestarSaldo", action = "http://vas.personal.com.py/IService1/PrestarSaldo")
    @WebResult(name = "PrestarSaldoResult", targetNamespace = "http://vas.personal.com.py")
    @RequestWrapper(localName = "PrestarSaldo", targetNamespace = "http://vas.personal.com.py", className = "py.com.personal.vas.PrestarSaldo")
    @ResponseWrapper(localName = "PrestarSaldoResponse", targetNamespace = "http://vas.personal.com.py", className = "py.com.personal.vas.PrestarSaldoResponse")
    public String prestarSaldo(
        @WebParam(name = "Usuario", targetNamespace = "http://vas.personal.com.py")
        String usuario,
        @WebParam(name = "Pass", targetNamespace = "http://vas.personal.com.py")
        String pass,
        @WebParam(name = "Aplicacion", targetNamespace = "http://vas.personal.com.py")
        String aplicacion,
        @WebParam(name = "LineaOrigen", targetNamespace = "http://vas.personal.com.py")
        String lineaOrigen);

    /**
     * 
     * @param aplicacion
     * @param usuario
     * @param lineaDestino
     * @param lineaOrigen
     * @param pass
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "PedirSaldo", action = "http://vas.personal.com.py/IService1/PedirSaldo")
    @WebResult(name = "PedirSaldoResult", targetNamespace = "http://vas.personal.com.py")
    @RequestWrapper(localName = "PedirSaldo", targetNamespace = "http://vas.personal.com.py", className = "py.com.personal.vas.PedirSaldo")
    @ResponseWrapper(localName = "PedirSaldoResponse", targetNamespace = "http://vas.personal.com.py", className = "py.com.personal.vas.PedirSaldoResponse")
    public String pedirSaldo(
        @WebParam(name = "Usuario", targetNamespace = "http://vas.personal.com.py")
        String usuario,
        @WebParam(name = "Pass", targetNamespace = "http://vas.personal.com.py")
        String pass,
        @WebParam(name = "Aplicacion", targetNamespace = "http://vas.personal.com.py")
        String aplicacion,
        @WebParam(name = "LineaOrigen", targetNamespace = "http://vas.personal.com.py")
        String lineaOrigen,
        @WebParam(name = "LineaDestino", targetNamespace = "http://vas.personal.com.py")
        String lineaDestino);

    /**
     * 
     * @param aplicacion
     * @param usuario
     * @param lineaOrigen
     * @param pass
     * @return
     *     returns org.datacontract.schemas._2004._07.mimundoussd.ArrayOfPlanes
     */
    @WebMethod(operationName = "ObtenerPlanes", action = "http://vas.personal.com.py/IService1/ObtenerPlanes")
    @WebResult(name = "ObtenerPlanesResult", targetNamespace = "http://vas.personal.com.py")
    @RequestWrapper(localName = "ObtenerPlanes", targetNamespace = "http://vas.personal.com.py", className = "py.com.personal.vas.ObtenerPlanes")
    @ResponseWrapper(localName = "ObtenerPlanesResponse", targetNamespace = "http://vas.personal.com.py", className = "py.com.personal.vas.ObtenerPlanesResponse")
    public ArrayOfPlanes obtenerPlanes(
        @WebParam(name = "Usuario", targetNamespace = "http://vas.personal.com.py")
        String usuario,
        @WebParam(name = "Pass", targetNamespace = "http://vas.personal.com.py")
        String pass,
        @WebParam(name = "Aplicacion", targetNamespace = "http://vas.personal.com.py")
        String aplicacion,
        @WebParam(name = "LineaOrigen", targetNamespace = "http://vas.personal.com.py")
        String lineaOrigen);

    /**
     * 
     * @param aplicacion
     * @param usuario
     * @param lineaOrigen
     * @param pass
     * @return
     *     returns org.datacontract.schemas._2004._07.mimundoussd.Personas
     */
    @WebMethod(operationName = "ObtenerDatos", action = "http://vas.personal.com.py/IService1/ObtenerDatos")
    @WebResult(name = "ObtenerDatosResult", targetNamespace = "http://vas.personal.com.py")
    @RequestWrapper(localName = "ObtenerDatos", targetNamespace = "http://vas.personal.com.py", className = "py.com.personal.vas.ObtenerDatos")
    @ResponseWrapper(localName = "ObtenerDatosResponse", targetNamespace = "http://vas.personal.com.py", className = "py.com.personal.vas.ObtenerDatosResponse")
    public Personas obtenerDatos(
        @WebParam(name = "Usuario", targetNamespace = "http://vas.personal.com.py")
        String usuario,
        @WebParam(name = "Pass", targetNamespace = "http://vas.personal.com.py")
        String pass,
        @WebParam(name = "Aplicacion", targetNamespace = "http://vas.personal.com.py")
        String aplicacion,
        @WebParam(name = "LineaOrigen", targetNamespace = "http://vas.personal.com.py")
        String lineaOrigen);

    /**
     * 
     * @param aplicacion
     * @param usuario
     * @param lineaOrigen
     * @param pass
     * @return
     *     returns com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfstring
     */
    @WebMethod(operationName = "ObtenerMontosRecFact", action = "http://vas.personal.com.py/IService1/ObtenerMontosRecFact")
    @WebResult(name = "ObtenerMontosRecFactResult", targetNamespace = "http://vas.personal.com.py")
    @RequestWrapper(localName = "ObtenerMontosRecFact", targetNamespace = "http://vas.personal.com.py", className = "py.com.personal.vas.ObtenerMontosRecFact")
    @ResponseWrapper(localName = "ObtenerMontosRecFactResponse", targetNamespace = "http://vas.personal.com.py", className = "py.com.personal.vas.ObtenerMontosRecFactResponse")
    public ArrayOfstring obtenerMontosRecFact(
        @WebParam(name = "Usuario", targetNamespace = "http://vas.personal.com.py")
        String usuario,
        @WebParam(name = "Pass", targetNamespace = "http://vas.personal.com.py")
        String pass,
        @WebParam(name = "Aplicacion", targetNamespace = "http://vas.personal.com.py")
        String aplicacion,
        @WebParam(name = "LineaOrigen", targetNamespace = "http://vas.personal.com.py")
        String lineaOrigen);

    /**
     * 
     * @param porcentaje
     * @param aplicacion
     * @param usuario
     * @param lineaOrigen
     * @param monto
     * @param pass
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "AcreditarMontosRecFact", action = "http://vas.personal.com.py/IService1/AcreditarMontosRecFact")
    @WebResult(name = "AcreditarMontosRecFactResult", targetNamespace = "http://vas.personal.com.py")
    @RequestWrapper(localName = "AcreditarMontosRecFact", targetNamespace = "http://vas.personal.com.py", className = "py.com.personal.vas.AcreditarMontosRecFact")
    @ResponseWrapper(localName = "AcreditarMontosRecFactResponse", targetNamespace = "http://vas.personal.com.py", className = "py.com.personal.vas.AcreditarMontosRecFactResponse")
    public String acreditarMontosRecFact(
        @WebParam(name = "Usuario", targetNamespace = "http://vas.personal.com.py")
        String usuario,
        @WebParam(name = "Pass", targetNamespace = "http://vas.personal.com.py")
        String pass,
        @WebParam(name = "Aplicacion", targetNamespace = "http://vas.personal.com.py")
        String aplicacion,
        @WebParam(name = "LineaOrigen", targetNamespace = "http://vas.personal.com.py")
        String lineaOrigen,
        @WebParam(name = "Porcentaje", targetNamespace = "http://vas.personal.com.py")
        String porcentaje,
        @WebParam(name = "Monto", targetNamespace = "http://vas.personal.com.py")
        String monto);

    /**
     * 
     * @param aplicacion
     * @param usuario
     * @param lineaOrigen
     * @param pass
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ObtenerPuntosCercanos", action = "http://vas.personal.com.py/IService1/ObtenerPuntosCercanos")
    @WebResult(name = "ObtenerPuntosCercanosResult", targetNamespace = "http://vas.personal.com.py")
    @RequestWrapper(localName = "ObtenerPuntosCercanos", targetNamespace = "http://vas.personal.com.py", className = "py.com.personal.vas.ObtenerPuntosCercanos")
    @ResponseWrapper(localName = "ObtenerPuntosCercanosResponse", targetNamespace = "http://vas.personal.com.py", className = "py.com.personal.vas.ObtenerPuntosCercanosResponse")
    public String obtenerPuntosCercanos(
        @WebParam(name = "Usuario", targetNamespace = "http://vas.personal.com.py")
        String usuario,
        @WebParam(name = "Pass", targetNamespace = "http://vas.personal.com.py")
        String pass,
        @WebParam(name = "Aplicacion", targetNamespace = "http://vas.personal.com.py")
        String aplicacion,
        @WebParam(name = "LineaOrigen", targetNamespace = "http://vas.personal.com.py")
        String lineaOrigen);

    /**
     * 
     * @param aplicacion
     * @param usuario
     * @param lineaOrigen
     * @param pass
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "EnviarConfiguracion", action = "http://vas.personal.com.py/IService1/EnviarConfiguracion")
    @WebResult(name = "EnviarConfiguracionResult", targetNamespace = "http://vas.personal.com.py")
    @RequestWrapper(localName = "EnviarConfiguracion", targetNamespace = "http://vas.personal.com.py", className = "py.com.personal.vas.EnviarConfiguracion")
    @ResponseWrapper(localName = "EnviarConfiguracionResponse", targetNamespace = "http://vas.personal.com.py", className = "py.com.personal.vas.EnviarConfiguracionResponse")
    public Boolean enviarConfiguracion(
        @WebParam(name = "Usuario", targetNamespace = "http://vas.personal.com.py")
        String usuario,
        @WebParam(name = "Pass", targetNamespace = "http://vas.personal.com.py")
        String pass,
        @WebParam(name = "Aplicacion", targetNamespace = "http://vas.personal.com.py")
        String aplicacion,
        @WebParam(name = "LineaOrigen", targetNamespace = "http://vas.personal.com.py")
        String lineaOrigen);

    /**
     * 
     * @param activacion
     * @param aplicacion
     * @param cantidadLineas
     * @param usuario
     * @param descripcion
     * @param numeroContacto
     * @param lineaOrigen
     * @param pass
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "ActivarNuevasLineas", action = "http://vas.personal.com.py/IService1/ActivarNuevasLineas")
    @WebResult(name = "ActivarNuevasLineasResult", targetNamespace = "http://vas.personal.com.py")
    @RequestWrapper(localName = "ActivarNuevasLineas", targetNamespace = "http://vas.personal.com.py", className = "py.com.personal.vas.ActivarNuevasLineas")
    @ResponseWrapper(localName = "ActivarNuevasLineasResponse", targetNamespace = "http://vas.personal.com.py", className = "py.com.personal.vas.ActivarNuevasLineasResponse")
    public Boolean activarNuevasLineas(
        @WebParam(name = "Usuario", targetNamespace = "http://vas.personal.com.py")
        String usuario,
        @WebParam(name = "Pass", targetNamespace = "http://vas.personal.com.py")
        String pass,
        @WebParam(name = "Aplicacion", targetNamespace = "http://vas.personal.com.py")
        String aplicacion,
        @WebParam(name = "LineaOrigen", targetNamespace = "http://vas.personal.com.py")
        String lineaOrigen,
        @WebParam(name = "CantidadLineas", targetNamespace = "http://vas.personal.com.py")
        String cantidadLineas,
        @WebParam(name = "NumeroContacto", targetNamespace = "http://vas.personal.com.py")
        String numeroContacto,
        @WebParam(name = "Descripcion", targetNamespace = "http://vas.personal.com.py")
        String descripcion,
        @WebParam(name = "Activacion", targetNamespace = "http://vas.personal.com.py")
        Boolean activacion);

    /**
     * 
     * @param lineaSuspendida
     * @param parametro1
     * @param aplicacion
     * @param usuario
     * @param parametro
     * @param lineaOrigen
     * @param accion
     * @param pass
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SuspenderLineas", action = "http://vas.personal.com.py/IService1/SuspenderLineas")
    @WebResult(name = "SuspenderLineasResult", targetNamespace = "http://vas.personal.com.py")
    @RequestWrapper(localName = "SuspenderLineas", targetNamespace = "http://vas.personal.com.py", className = "py.com.personal.vas.SuspenderLineas")
    @ResponseWrapper(localName = "SuspenderLineasResponse", targetNamespace = "http://vas.personal.com.py", className = "py.com.personal.vas.SuspenderLineasResponse")
    public String suspenderLineas(
        @WebParam(name = "Usuario", targetNamespace = "http://vas.personal.com.py")
        String usuario,
        @WebParam(name = "Pass", targetNamespace = "http://vas.personal.com.py")
        String pass,
        @WebParam(name = "Aplicacion", targetNamespace = "http://vas.personal.com.py")
        String aplicacion,
        @WebParam(name = "LineaOrigen", targetNamespace = "http://vas.personal.com.py")
        String lineaOrigen,
        @WebParam(name = "LineaSuspendida", targetNamespace = "http://vas.personal.com.py")
        String lineaSuspendida,
        @WebParam(name = "Accion", targetNamespace = "http://vas.personal.com.py")
        String accion,
        @WebParam(name = "Parametro", targetNamespace = "http://vas.personal.com.py")
        String parametro,
        @WebParam(name = "Parametro1", targetNamespace = "http://vas.personal.com.py")
        String parametro1);

    /**
     * 
     * @param aplicacion
     * @param usuario
     * @param lineaOrigen
     * @param pass
     * @return
     *     returns org.datacontract.schemas._2004._07.mimundoussd.Usuarios
     */
    @WebMethod(operationName = "ObtenerEstado", action = "http://vas.personal.com.py/IService1/ObtenerEstado")
    @WebResult(name = "ObtenerEstadoResult", targetNamespace = "http://vas.personal.com.py")
    @RequestWrapper(localName = "ObtenerEstado", targetNamespace = "http://vas.personal.com.py", className = "py.com.personal.vas.ObtenerEstado")
    @ResponseWrapper(localName = "ObtenerEstadoResponse", targetNamespace = "http://vas.personal.com.py", className = "py.com.personal.vas.ObtenerEstadoResponse")
    public Usuarios obtenerEstado(
        @WebParam(name = "Usuario", targetNamespace = "http://vas.personal.com.py")
        String usuario,
        @WebParam(name = "Pass", targetNamespace = "http://vas.personal.com.py")
        String pass,
        @WebParam(name = "Aplicacion", targetNamespace = "http://vas.personal.com.py")
        String aplicacion,
        @WebParam(name = "LineaOrigen", targetNamespace = "http://vas.personal.com.py")
        String lineaOrigen);

    /**
     * 
     * @param aplicacion
     * @param usuario
     * @param lineaOrigen
     * @param nuevaClave
     * @param pass
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "ResetearClave", action = "http://vas.personal.com.py/IService1/ResetearClave")
    @WebResult(name = "ResetearClaveResult", targetNamespace = "http://vas.personal.com.py")
    @RequestWrapper(localName = "ResetearClave", targetNamespace = "http://vas.personal.com.py", className = "py.com.personal.vas.ResetearClave")
    @ResponseWrapper(localName = "ResetearClaveResponse", targetNamespace = "http://vas.personal.com.py", className = "py.com.personal.vas.ResetearClaveResponse")
    public Boolean resetearClave(
        @WebParam(name = "Usuario", targetNamespace = "http://vas.personal.com.py")
        String usuario,
        @WebParam(name = "Pass", targetNamespace = "http://vas.personal.com.py")
        String pass,
        @WebParam(name = "Aplicacion", targetNamespace = "http://vas.personal.com.py")
        String aplicacion,
        @WebParam(name = "LineaOrigen", targetNamespace = "http://vas.personal.com.py")
        String lineaOrigen,
        @WebParam(name = "NuevaClave", targetNamespace = "http://vas.personal.com.py")
        String nuevaClave);

    /**
     * 
     * @param aplicacion
     * @param usuario
     * @param lineaOrigen
     * @param pass
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "DesbloquearClave", action = "http://vas.personal.com.py/IService1/DesbloquearClave")
    @WebResult(name = "DesbloquearClaveResult", targetNamespace = "http://vas.personal.com.py")
    @RequestWrapper(localName = "DesbloquearClave", targetNamespace = "http://vas.personal.com.py", className = "py.com.personal.vas.DesbloquearClave")
    @ResponseWrapper(localName = "DesbloquearClaveResponse", targetNamespace = "http://vas.personal.com.py", className = "py.com.personal.vas.DesbloquearClaveResponse")
    public Boolean desbloquearClave(
        @WebParam(name = "Usuario", targetNamespace = "http://vas.personal.com.py")
        String usuario,
        @WebParam(name = "Pass", targetNamespace = "http://vas.personal.com.py")
        String pass,
        @WebParam(name = "Aplicacion", targetNamespace = "http://vas.personal.com.py")
        String aplicacion,
        @WebParam(name = "LineaOrigen", targetNamespace = "http://vas.personal.com.py")
        String lineaOrigen);

    /**
     * 
     * @param aplicacion
     * @param usuario
     * @param lineaDestino
     * @param mensaje
     * @param origen
     * @param pass
     */
    @WebMethod(operationName = "EnviarSms", action = "http://vas.personal.com.py/IService1/EnviarSms")
    @RequestWrapper(localName = "EnviarSms", targetNamespace = "http://vas.personal.com.py", className = "py.com.personal.vas.EnviarSms")
    @ResponseWrapper(localName = "EnviarSmsResponse", targetNamespace = "http://vas.personal.com.py", className = "py.com.personal.vas.EnviarSmsResponse")
    public void enviarSms(
        @WebParam(name = "Usuario", targetNamespace = "http://vas.personal.com.py")
        String usuario,
        @WebParam(name = "Pass", targetNamespace = "http://vas.personal.com.py")
        String pass,
        @WebParam(name = "Aplicacion", targetNamespace = "http://vas.personal.com.py")
        String aplicacion,
        @WebParam(name = "LineaDestino", targetNamespace = "http://vas.personal.com.py")
        String lineaDestino,
        @WebParam(name = "Mensaje", targetNamespace = "http://vas.personal.com.py")
        String mensaje,
        @WebParam(name = "Origen", targetNamespace = "http://vas.personal.com.py")
        String origen);

    /**
     * 
     * @param aplicacion
     * @param usuario
     * @param lineaOrigen
     * @param pass
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "MisBackTones", action = "http://vas.personal.com.py/IService1/MisBackTones")
    @WebResult(name = "MisBackTonesResult", targetNamespace = "http://vas.personal.com.py")
    @RequestWrapper(localName = "MisBackTones", targetNamespace = "http://vas.personal.com.py", className = "py.com.personal.vas.MisBackTones")
    @ResponseWrapper(localName = "MisBackTonesResponse", targetNamespace = "http://vas.personal.com.py", className = "py.com.personal.vas.MisBackTonesResponse")
    public Boolean misBackTones(
        @WebParam(name = "Usuario", targetNamespace = "http://vas.personal.com.py")
        String usuario,
        @WebParam(name = "Pass", targetNamespace = "http://vas.personal.com.py")
        String pass,
        @WebParam(name = "Aplicacion", targetNamespace = "http://vas.personal.com.py")
        String aplicacion,
        @WebParam(name = "LineaOrigen", targetNamespace = "http://vas.personal.com.py")
        String lineaOrigen);

    /**
     * 
     * @param aplicacion
     * @param usuario
     * @param lineaOrigen
     * @param pass
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "CancelarBackTone", action = "http://vas.personal.com.py/IService1/CancelarBackTone")
    @WebResult(name = "CancelarBackToneResult", targetNamespace = "http://vas.personal.com.py")
    @RequestWrapper(localName = "CancelarBackTone", targetNamespace = "http://vas.personal.com.py", className = "py.com.personal.vas.CancelarBackTone")
    @ResponseWrapper(localName = "CancelarBackToneResponse", targetNamespace = "http://vas.personal.com.py", className = "py.com.personal.vas.CancelarBackToneResponse")
    public String cancelarBackTone(
        @WebParam(name = "Usuario", targetNamespace = "http://vas.personal.com.py")
        String usuario,
        @WebParam(name = "Pass", targetNamespace = "http://vas.personal.com.py")
        String pass,
        @WebParam(name = "Aplicacion", targetNamespace = "http://vas.personal.com.py")
        String aplicacion,
        @WebParam(name = "LineaOrigen", targetNamespace = "http://vas.personal.com.py")
        String lineaOrigen);

    /**
     * 
     * @param aplicacion
     * @param usuario
     * @param lineaOrigen
     * @param pass
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "NuevoRbt", action = "http://vas.personal.com.py/IService1/NuevoRbt")
    @WebResult(name = "NuevoRbtResult", targetNamespace = "http://vas.personal.com.py")
    @RequestWrapper(localName = "NuevoRbt", targetNamespace = "http://vas.personal.com.py", className = "py.com.personal.vas.NuevoRbt")
    @ResponseWrapper(localName = "NuevoRbtResponse", targetNamespace = "http://vas.personal.com.py", className = "py.com.personal.vas.NuevoRbtResponse")
    public Boolean nuevoRbt(
        @WebParam(name = "Usuario", targetNamespace = "http://vas.personal.com.py")
        String usuario,
        @WebParam(name = "Pass", targetNamespace = "http://vas.personal.com.py")
        String pass,
        @WebParam(name = "Aplicacion", targetNamespace = "http://vas.personal.com.py")
        String aplicacion,
        @WebParam(name = "LineaOrigen", targetNamespace = "http://vas.personal.com.py")
        String lineaOrigen);

    /**
     * 
     * @param aplicacion
     * @param usuario
     * @param lineaOrigen
     * @param pass
     * @return
     *     returns com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfstring
     */
    @WebMethod(operationName = "ObtenerDestinosGratuitos", action = "http://vas.personal.com.py/IService1/ObtenerDestinosGratuitos")
    @WebResult(name = "ObtenerDestinosGratuitosResult", targetNamespace = "http://vas.personal.com.py")
    @RequestWrapper(localName = "ObtenerDestinosGratuitos", targetNamespace = "http://vas.personal.com.py", className = "py.com.personal.vas.ObtenerDestinosGratuitos")
    @ResponseWrapper(localName = "ObtenerDestinosGratuitosResponse", targetNamespace = "http://vas.personal.com.py", className = "py.com.personal.vas.ObtenerDestinosGratuitosResponse")
    public ArrayOfstring obtenerDestinosGratuitos(
        @WebParam(name = "Usuario", targetNamespace = "http://vas.personal.com.py")
        String usuario,
        @WebParam(name = "Pass", targetNamespace = "http://vas.personal.com.py")
        String pass,
        @WebParam(name = "Aplicacion", targetNamespace = "http://vas.personal.com.py")
        String aplicacion,
        @WebParam(name = "LineaOrigen", targetNamespace = "http://vas.personal.com.py")
        String lineaOrigen);

    /**
     * 
     * @param aplicacion
     * @param usuario
     * @param lineaOrigen
     * @param pass
     */
    @WebMethod(operationName = "DesactivarFyf", action = "http://vas.personal.com.py/IService1/DesactivarFyf")
    @RequestWrapper(localName = "DesactivarFyf", targetNamespace = "http://vas.personal.com.py", className = "py.com.personal.vas.DesactivarFyf")
    @ResponseWrapper(localName = "DesactivarFyfResponse", targetNamespace = "http://vas.personal.com.py", className = "py.com.personal.vas.DesactivarFyfResponse")
    public void desactivarFyf(
        @WebParam(name = "Usuario", targetNamespace = "http://vas.personal.com.py")
        String usuario,
        @WebParam(name = "Pass", targetNamespace = "http://vas.personal.com.py")
        String pass,
        @WebParam(name = "Aplicacion", targetNamespace = "http://vas.personal.com.py")
        String aplicacion,
        @WebParam(name = "LineaOrigen", targetNamespace = "http://vas.personal.com.py")
        String lineaOrigen);

    /**
     * 
     * @param aplicacion
     * @param usuario
     * @param lineaOrigen
     * @param pass
     */
    @WebMethod(operationName = "NuevoFyF", action = "http://vas.personal.com.py/IService1/NuevoFyF")
    @RequestWrapper(localName = "NuevoFyF", targetNamespace = "http://vas.personal.com.py", className = "py.com.personal.vas.NuevoFyF")
    @ResponseWrapper(localName = "NuevoFyFResponse", targetNamespace = "http://vas.personal.com.py", className = "py.com.personal.vas.NuevoFyFResponse")
    public void nuevoFyF(
        @WebParam(name = "Usuario", targetNamespace = "http://vas.personal.com.py")
        String usuario,
        @WebParam(name = "Pass", targetNamespace = "http://vas.personal.com.py")
        String pass,
        @WebParam(name = "Aplicacion", targetNamespace = "http://vas.personal.com.py")
        String aplicacion,
        @WebParam(name = "LineaOrigen", targetNamespace = "http://vas.personal.com.py")
        String lineaOrigen);

    /**
     * 
     * @param operacion
     * @param facturaFisica
     * @param aplicacion
     * @param email
     * @param usuario
     * @param lineaOrigen
     * @param pass
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "FacturaElectronica", action = "http://vas.personal.com.py/IService1/FacturaElectronica")
    @WebResult(name = "FacturaElectronicaResult", targetNamespace = "http://vas.personal.com.py")
    @RequestWrapper(localName = "FacturaElectronica", targetNamespace = "http://vas.personal.com.py", className = "py.com.personal.vas.FacturaElectronica")
    @ResponseWrapper(localName = "FacturaElectronicaResponse", targetNamespace = "http://vas.personal.com.py", className = "py.com.personal.vas.FacturaElectronicaResponse")
    public String facturaElectronica(
        @WebParam(name = "Usuario", targetNamespace = "http://vas.personal.com.py")
        String usuario,
        @WebParam(name = "Pass", targetNamespace = "http://vas.personal.com.py")
        String pass,
        @WebParam(name = "Aplicacion", targetNamespace = "http://vas.personal.com.py")
        String aplicacion,
        @WebParam(name = "LineaOrigen", targetNamespace = "http://vas.personal.com.py")
        String lineaOrigen,
        @WebParam(name = "Email", targetNamespace = "http://vas.personal.com.py")
        String email,
        @WebParam(name = "Operacion", targetNamespace = "http://vas.personal.com.py")
        String operacion,
        @WebParam(name = "FacturaFisica", targetNamespace = "http://vas.personal.com.py")
        String facturaFisica);

    /**
     * 
     * @param aplicacion
     * @param usuario
     * @param nuevoMail
     * @param lineaOrigen
     * @param pass
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "CambiarMail", action = "http://vas.personal.com.py/IService1/CambiarMail")
    @WebResult(name = "CambiarMailResult", targetNamespace = "http://vas.personal.com.py")
    @RequestWrapper(localName = "CambiarMail", targetNamespace = "http://vas.personal.com.py", className = "py.com.personal.vas.CambiarMail")
    @ResponseWrapper(localName = "CambiarMailResponse", targetNamespace = "http://vas.personal.com.py", className = "py.com.personal.vas.CambiarMailResponse")
    public String cambiarMail(
        @WebParam(name = "Usuario", targetNamespace = "http://vas.personal.com.py")
        String usuario,
        @WebParam(name = "Pass", targetNamespace = "http://vas.personal.com.py")
        String pass,
        @WebParam(name = "Aplicacion", targetNamespace = "http://vas.personal.com.py")
        String aplicacion,
        @WebParam(name = "LineaOrigen", targetNamespace = "http://vas.personal.com.py")
        String lineaOrigen,
        @WebParam(name = "NuevoMail", targetNamespace = "http://vas.personal.com.py")
        String nuevoMail);

}
